### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by przepompownia** [ldelossa/litee-symboltree.nvim#3]
I'd like to try this view both in panel and float window but it's not as easy as its documentation says. 

It seems that it was up to date in past year. See `git log -S` on `litee-config` or `ws_lsp_handler` on litee.nvim. 

Please upgrade the docs according to the latest changes.

**Comment by ldelossa** [comment]
Im sorry, what issue are you running into?

**Comment by przepompownia** [comment]
It has source at least in #4 but in general, it would be good to review and upgrade README and vimdoc to avoid user confusion and save user's time (and, in effect, encourage to try litee-symboltree).

**Comment by ldelossa** [comment]
Agreed, a documentation pass has to be done.

**Comment by przepompownia** [comment]
I found (in your dotfiles and later in marshal.lua) that we have not keep `icon_set` under `tree` (as the doc says):

https://github.com/ldelossa/litee-symboltree.nvim/blob/main/doc/litee-symboltree.txt#L192

I thought that is litee-level configuration.

**Comment by ldelossa** [comment]
what you linked to just defines the icon used for the base tree icons such as "expanded", "collapsed", "indent_guide" etc... 

other plugins can import lib/icon and use what ever icons they like when rendering their marshal_funcs.

also performed documentation passes last night, updated readme and docs so closing this.
