### ISSUE TITLE
Make cmd/keymap UI more configurable

### ISSUE THREAD

**Issue by przepompownia** [ldelossa/litee-symboltree.nvim#7]
Currently 
- the command set is hardcoded but could be optional - I will probably never (or very rarely) have to use any of them 
- fixed keystrokes are used to keymaps - it would be good provide a method to easy replace the default values. I am looking at `function M._setup_buffer(name, buf, tab)` and do not see such easy solution.

**Comment by ldelossa** [comment]
The idea with key mapping is, anything you can do in a buffer you can do with an "LT*" command. 

You can map "LT*" commands to any key stroke you want, "LT*" commands work regardless of whether you're in the symboltree or not. 

Why remove the defaults if you do not need to use them?

**Comment by ldelossa** [comment]
That being said, I will except a PR which optionally maps the buffer local keystrokes. 

I don't think I'd accept a PR which just never maps any "LT*" commands. This is odd for a plugin to do.

**Comment by przepompownia** [comment]
Would you like to maintain compatibility with some minimal nvim version e.g. the latest stable? 

It matters because since week we can 
```lua
require('vim.keymap').set({'n'}, 'H', function require('litee.lib.util.buffer').hide_cursor(false) end, {buffer = buf})
```
instead of indirect calling it through a vim command.

**Comment by ldelossa** [comment]
Im fine with following Neovim latest stable releases. Dont want to follow nightly or bleeding edge.
